// This file is automatically generated. Do not edit it directly.
// NOTE: Replaced the remote Supabase client with our local stub implementation
// This ensures the entire application runs locally without external dependencies.

// Import the local-only Supabase stub (defined in src/lib/supabase.ts)
import { supabase as localSupabase } from "@/lib/supabase";

// Re‑export so existing imports ("@/integrations/supabase/client") keep working
export const supabase = localSupabase;
